services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend-api:
    build: ./backend
    container_name: backend-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowbit
      - JWT_SECRET=${JWT_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./backend:/app
    restart: always

  react-shell:
    build: ./react-shell
    container_name: react-shell
    ports:
      - "4001:4001"
    volumes:
      - ./react-shell:/app
    depends_on:
      - backend-api

  support-tickets-app:
    build: ./support-tickets-app
    container_name: support-tickets-app
    ports:
      - "3100:3100"
    volumes:
      - ./support-tickets-app:/app
    depends_on:
      - backend-api

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://ngrok:4040
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http backend-api:3000

volumes:
  mongo-data:
